# Generated by Django 4.1 on 2023-12-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='publica',
            field=models.BooleanField(default=False),
        ),
    ]
