# Generated by Django 4.1 on 2023-12-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='publica',
            new_name='publicada',
        ),
    ]
